import { Platform } from '../types';

export interface GeneratedFile {
  path: string;
  content: string;
  platform: Platform;
}

export interface GeneratorOptions {
  platform: Platform | 'all';
  outputDir?: string;
  overwrite?: boolean;
  dryRun?: boolean;
}

export abstract class BaseGenerator<TInput = any> {
  abstract readonly name: string;
  abstract readonly supportedPlatforms: Platform[];

  abstract validate(input: TInput): void;
  abstract generate(input: TInput, options: GeneratorOptions): GeneratedFile[];

  protected getPlatforms(requestedPlatform: Platform | 'all'): Platform[] {
    if (requestedPlatform === 'all') {
      return this.supportedPlatforms;
    }

    if (!this.supportedPlatforms.includes(requestedPlatform)) {
      throw new Error(
        `Platform ${requestedPlatform} is not supported by ${this.name} generator. ` +
        `Supported platforms: ${this.supportedPlatforms.join(', ')}`
      );
    }

    return [requestedPlatform];
  }

  protected createFileHeader(sourceFile: string): string {
    const timestamp = new Date().toISOString().split('T')[0];
    return [
      `// Generated by cuppa-cli from ${sourceFile}`,
      `// Generation date: ${timestamp}`,
      `// DO NOT EDIT MANUALLY - Changes will be overwritten`,
      '',
    ].join('\n');
  }
}
