import { ParsedModel, ParsedProperty } from './json-schema-types';

export class KotlinModelGenerator {
  generate(model: ParsedModel, sourceFile: string): string {
    const lines: string[] = [];

    // Header
    lines.push(this.createHeader(sourceFile));
    lines.push('import kotlinx.serialization.Serializable');
    lines.push('');

    // Documentation
    if (model.description) {
      lines.push(`/**`);
      lines.push(` * ${model.description}`);
      lines.push(` */`);
    }

    // Data class declaration
    lines.push(`@Serializable`);
    lines.push(`data class ${model.name}(`);

    // Properties
    const properties = model.properties.map((prop, index) => {
      return this.generateProperty(prop, index === model.properties.length - 1);
    });

    lines.push(...properties);
    lines.push(`)`);
    lines.push('');

    return lines.join('\n');
  }

  private createHeader(sourceFile: string): string {
    const timestamp = new Date().toISOString().split('T')[0];
    return [
      `// Generated by cuppa-cli from ${sourceFile}`,
      `// Generation date: ${timestamp}`,
      `// DO NOT EDIT MANUALLY - Changes will be overwritten`,
      '',
    ].join('\n');
  }

  private generateProperty(prop: ParsedProperty, isLast: boolean): string {
    const kotlinType = this.mapToKotlinType(prop);
    const defaultValue = prop.optional ? ' = null' : '';
    const comma = isLast ? '' : ',';

    const lines: string[] = [];

    // Documentation
    if (prop.description) {
      lines.push(`    /** ${prop.description} */`);
    }

    // Property declaration
    lines.push(`    val ${prop.name}: ${kotlinType}${defaultValue}${comma}`);

    return lines.join('\n');
  }

  private mapToKotlinType(prop: ParsedProperty): string {
    let baseType = this.getBaseKotlinType(prop.type, prop.format);

    if (prop.isArray) {
      baseType = `List<${baseType}>`;
    }

    if (prop.optional) {
      baseType = `${baseType}?`;
    }

    return baseType;
  }

  private getBaseKotlinType(type: string, format?: string): string {
    // Handle format-specific types
    if (format) {
      switch (format) {
        case 'uuid':
          return 'String'; // or java.util.UUID
        case 'date':
        case 'date-time':
          return 'String'; // or kotlinx.datetime.LocalDateTime
        case 'uri':
        case 'url':
          return 'String';
        case 'email':
          return 'String';
      }
    }

    // Handle basic types
    switch (type) {
      case 'string':
        return 'String';
      case 'integer':
        return 'Int';
      case 'number':
        return 'Double';
      case 'boolean':
        return 'Boolean';
      case 'object':
        return 'Map<String, Any>';
      case 'array':
        return 'List<Any>';
      default:
        return 'String'; // Fallback
    }
  }
}
